#!/bin/bash

echo "#################"
echo "    COMPILING    "
echo "#################"

g++ -Wall -std=c++11 -O3 src/main.cpp src/file2 -o network

echo "#################"
echo "     RUNNING     "
echo "#################"

./network
