#!/bin/bash

echo "#################"
echo "    COMPILING    "
echo "#################"

g++ -std=c++11 -O3 src/test_neuralNetworkNLayer.cpp -o network

echo "#################"
echo "     RUNNING     "
echo "#################"

./network
